# Arquivo de definição de labels para o repositório
# Utilize nomes, cores e descrições para facilitar a organização de issues

- name: "tipo:bug"
  color: "d73a4a"
  description: "Problema ou erro no sistema"
- name: "tipo:feature"
  color: "a2eeef"
  description: "Nova funcionalidade ou melhoria"
- name: "tipo:task"
  color: "7057ff"
  description: "Tarefa ou atividade"
- name: "prioridade:alta"
  color: "b60205"
  description: "Alta prioridade"
- name: "prioridade:média"
  color: "d93f0b"
  description: "Média prioridade"
- name: "prioridade:baixa"
  color: "0e8a16"
  description: "Baixa prioridade"
- name: "status:backlog"
  color: "fbca04"
  description: "Aguardando planejamento"
- name: "status:planejado"
  color: "0075ca"
  description: "Planejado para ser iniciado"
- name: "status:em progresso"
  color: "0e8a16"
  description: "Atividade em andamento"
- name: "status:em revisão"
  color: "5319e7"
  description: "Em processo de revisão"
- name: "status:concluído"
  color: "1d76db"
  description: "Atividade concluída"
- name: "tipo:épico"
  color: "6f42c1"
  description: "Grande iniciativa ou projeto"
