site_name: API Loja de Construção
site_description: Documentação oficial da API Loja de Construção
site_url: https://MarcoTulioSoares.github.io/mkdocs-site
repo_url: https://github.com/MarcoTulioSoares/mkdocs-site
repo_name: MarcoTulioSoares/mkdocs-site

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Visão Geral: index.md
  - Arquitetura: sobre.md
  - API REST: api.md
  - Backlog: backlog.md
  - Contribuindo: contribuindo.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
